# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ifo
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima


# Permalinks
#permalink: /:year-:month-:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile

# Permalinks
permalink: /:year-:month-:day/:title

headerLogo: /resource/logo.jpg

headerText: 运营的专业分叉信息站
headerHref: 比特派

headerMenu:
  - menuTitle: 比特分叉
    id: btfork
    menuList:
      - menuName: 全部
        id: btall
      - menuName: 即将分叉
        id: bting
      - menuName: 已分叉
        id: btend
      - menuName: 分叉中
        id: btstart
  - menuTitle: 以太分叉
    id: ethfork
    menuList:
      - menuName: 全部
        id: ethall
      - menuName: 即将分叉
        id: ething
      - menuName: 已分叉
        id: ethend
      - menuName: 分叉中
        id: ethstart
  - menuTitle: 莱特分叉
    id: ltcfork
    menuList:
      - menuName: 全部
        id: ltcall
      - menuName: 即将分叉
        id: ltcing
      - menuName: 已分叉
        id: ltcend
      - menuName: 分叉中
        id: ltcstart
  - menuTitle: 糖果
    id: candy
    menuList:
      - menuName: 全部
        id: candyall
      - menuName: 进行中
        id: candying
      - menuName: 已结束
        id: candyend
  - menuTitle: ifo服务
    id: ifoservice
  - menuTitle: 中/En
    id: language

defaultType:
  - menuName: 全部
    id: all
  - menuName: 即将分叉
    id: ing
  - menuName: 已分叉
    id: end
  - menuName: 分叉中
    id: start

footer:
  - donatio: 捐赠地址：1Bitpie7nzdqcsHWYMVi4ePuY88hF2jr7E
    qrcode: ../resource/donate.png
    support: Pieifo是由比特派运营的专业分叉类信息站 Powered by
    supportHref: Bitpie.com


headerMenuEn:
  - menuTitle: BTC Forks
    id: btfork
    menuList:
      - menuName: All
        id: btall
      - menuName: Upcoming
        id: bting
      - menuName: Completed
        id: btend
      - menuName: Undergoing
        id: btstart
  - menuTitle: ETH Forks
    id: ethfork
    menuList:
      - menuName: All
        id: ethall
      - menuName: Upcoming
        id: ething
      - menuName: Completed
        id: ethend
      - menuName: Undergoing
        id: ethstart
  - menuTitle: LTC Forks
    id: ltcfork
    menuList:
      - menuName: All
        id: ltcall
      - menuName: Upcoming
        id: ltcing
      - menuName: Completed
        id: ltcend
      - menuName: Undergoing
        id: ltcstart
  - menuTitle: Airdrop
    id: candy
    menuList:
      - menuName: All
        id: candyall
      - menuName: Undergoing
        id: candying
      - menuName: Cancelled
        id: candyend
  - menuTitle: IFO Service
    id: ifoservice
  - menuTitle: 中/En
    id: language

footerEn:
  - donatio: Donation:1Bitpie7nzdqcsHWYMVi4ePuY88hF2jr7E
    qrcode: ../resource/donate.png
    support: The most professional IFO portal powered by
    supportHref: Bitpie.com

defaultTypeEn:
  - menuName: All
    id: all
  - menuName: Upcoming
    id: ing
  - menuName: Completed
    id: end
  - menuName: Undergoing
    id: start

headerTextEn: The most Professional IFO Portal powered by
headerHrefEn: Bitpie
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

