# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ifo
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile

headerLogo: /resource/logo.jpg

headerMenu:
  - menuTitle: 比特分叉
    id: btfork
    menuList:
      - menuName: 全部
        id: btall
      - menuName: 即将分叉
        id: bting
      - menuName: 已分叉
        id: btend
      - menuName: 分叉中
        id: btstart
  - menuTitle: 以太分叉
    id: ethfork
    menuList:
      - menuName: 全部
        id: ethall
      - menuName: 即将分叉
        id: ething
      - menuName: 已分叉
        id: ethend
      - menuName: 分叉中
        id: ethstart
  - menuTitle: 莱特分叉
    id: ltcfork
    menuList:
      - menuName: 全部
        id: ltcall
      - menuName: 即将分叉
        id: ltcing
      - menuName: 已分叉
        id: ltcend
      - menuName: 分叉中
        id: ltcstart
  - menuTitle: 糖果
    id: candy
    menuList:
      - menuName: 全部
        id: candyall
      - menuName: 进行中
        id: candying
      - menuName: 已结束
        id: candyend
  - menuTitle: ifo服务
    id: ifoservice

defaultType:
  - menuName: 全部
    id: all
  - menuName: 即将分叉
    id: ing
  - menuName: 已分叉
    id: end
  - menuName: 分叉中
    id: start


coinForkInfo:
  - imageHref: /pages/ubdetail
    imageUrl: /resource/ub.jpg
    coinName: 联合比特币(UBTC)
    coinInfo: 支持智能合约和闪电网络的比特币
    blockHightTitle: 分叉高度
    blockHight: 498777
    timeTitle: 倒计时
    timeTitleClass: ubtimetitle
    time: 2017/12/12
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: ubhight
    timeClass: ub
    btnTitle: 查看详情
    btnHref: /pages/ubdetail
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/bcxdetail
    imageUrl: /resource/default.jpg
    coinName: 比特无限(BCX)
    coinInfo: Bitcoin X 结合了零知识证明，智能合约，并会在未来更改为DPOS共识机制
    blockHightTitle: 分叉高度
    blockHight: 498888
    timeTitle: 倒计时
    timeTitleClass: bcxdtimetitle
    time: 2017/12/13
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: bcxhight
    timeClass: bcx
    btnTitle: 查看详情
    btnHref: /pages/bcxdetail
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/btpaydetail
    imageUrl: /resource/btpay.jpg
    coinName: 比特币支付
    coinInfo: 比特币支付致力于建立更便捷的全球支付生态
    blockHightTitle: 分叉高度
    blockHight: 499345
    timeTitle: 倒计时
    timeTitleClass: btpaytimetitle
    time: 2017/12/16
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: btpayhight
    timeClass: btpay
    btnTitle: 查看详情
    btnHref: /pages/btpaydetail
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/sbtcdetail
    imageUrl: /resource/sbtc.jpg
    coinName: 超级比特币(SBTC)
    coinInfo: 让比特币网络拥有智能合约
    blockHightTitle: 分叉高度
    blockHight: 498888
    timeTitle: 倒计时
    timeTitleClass: sbtcdtimetitle
    time: 2017/12/17
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: sbtchight
    timeClass: sbtc
    btnTitle: 查看详情
    btnHref: /pages/sbtcdetail
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/bcwdetail
    imageUrl: /resource/default.jpg
    coinName: Bitcoin World(BCW)
    coinInfo: BCW旨在创建一个更快捷、更分散、更智能、更安全、更隐私的分叉币
    blockHightTitle: 分叉高度
    blockHight: 499777
    timeTitle: 倒计时
    timeTitleClass: bcwtimetitle
    time: 2017/12/19
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: bcwhight
    timeClass: bcw
    btnTitle: 查看详情
    btnHref: /pages/bcwdetail
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/lbtcdetail.html
    imageUrl: /resource/lbtc.jpg
    coinName: 闪电比特币(LBTC)
    coinInfo: 引入DPOS共识机制
    blockHightTitle: 分叉高度
    blockHight: 499999
    timeTitle: 倒计时
    timeTitleClass: lbtctimetitle
    time: 2017/12/23
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: lbtchight
    timeClass: lbtc
    btnTitle: 查看详情
    btnHref: /pages/lbtcdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/btpdetail
    imageUrl: /resource/btp.jpg
    coinName: 比特币白金(BTP)
    coinInfo: 分叉高度由496525推迟至498533
    blockHightTitle: 分叉高度
    blockHight: 500000
    timeTitle: 倒计时
    timeTitleClass: btptimetitle
    time: 2017/12/23
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: btphight
    timeClass: btp
    btnTitle: 查看详情
    btnHref: /pages/btpdetail
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/goddetail.html
    imageUrl: /resource/default.jpg
    coinName: 比特币上帝(BTG)
    coinInfo: 社区自治的分叉
    blockHightTitle: 分叉高度
    blockHight: 501225
    timeTitle: 加载中
    timeTitleClass: godtimetitle
    time: 2017/12/25
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: godhight
    timeClass: god
    btnTitle: 查看详情
    btnHref: /pages/goddetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/bckdetail.html
    imageUrl: /resource/default.jpg
    coinName: 比特君主(BCK)
    coinInfo: 低费率的电子现金系统
    blockHightTitle: 分叉高度
    blockHight: 499999
    timeTitle: 加载中
    timeTitleClass: bcktimetitle
    time: 2017/12/25
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: bckhight
    timeClass: king
    btnTitle: 查看详情
    btnHref: /pages/bckdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/uraniumdetail.html
    imageUrl: /resource/uranium.jpg
    coinName: 比特铀(BTU)
    coinInfo: 采用equhash算法
    blockHightTitle: 分叉高度
    blockHight: 未公布
    timeTitle: 预估分叉日期
    timeTitleClass: uraniumtimetitle
    time: 2017/12/31
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: uraniumhight
    timeClass: uranium
    btnTitle: 查看详情
    btnHref: /pages/uraniumdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/ethfogdetail.html
    imageUrl: /resource/default.jpg
    coinName: 以太雾(ETF)
    coinInfo: 发展为下一代雾计算平台
    blockHightTitle: 分叉高度
    blockHight: 4830000
    timeTitle: 预估分叉日期
    timeTitleClass: uraniumtimetitle
    time: 2018/1/1
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: ethfoghight
    timeClass: ethfog
    btnTitle: 查看详情
    btnHref: /pages/ethfogdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: ethForkInfo
  - imageHref: /pages/plusdetail.html
    imageUrl: /resource/plus.jpg
    coinName: 比特币增强现金(BCP)
    coinInfo: 低费率的电子现金系统
    blockHightTitle: 分叉高度
    blockHight: 501407
    timeTitle: 倒计时
    timeTitleClass: plustimetitle
    time: 2018/1/2
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: plushight
    timeClass: plus
    btnTitle: 查看详情
    btnHref: /pages/plusdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/ltcsltcdetail.html
    imageUrl: /resource/default.jpg
    coinName: 超级莱特币(SLTC)
    coinInfo: 基于莱特币网络的硬分叉
    blockHightTitle: 分叉高度
    blockHight: 1343999
    timeTitle: 倒计时
    timeTitleClass: ltcsltctimetitle
    time: 2018/1/5
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: ltcsltchight
    timeClass: ltcsltc
    btnTitle: 查看详情
    btnHref: /pages/ltcsltcdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: ltcForkInfo
  - imageHref: /pages/ltcltsdetail.html
    imageUrl: /resource/default.jpg
    coinName: 莱特股(LTS)
    coinInfo: 引入POS机制
    blockHightTitle: 分叉高度
    blockHight: 1359668
    timeTitle: 倒计时
    timeTitleClass: ltcltstimetitle
    time: 2018/1/15
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: ltcltshight
    timeClass: ltclts
    btnTitle: 查看详情
    btnHref: /pages/ltcltsdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: ltcForkInfo
  - imageHref: /pages/silverdetail.html
    imageUrl: /resource/silver.jpg
    coinName: 比特币白银(BTS)
    coinInfo: 主要对挖矿算法进行更新使全网算力更加分散
    blockHightTitle: 分叉高度
    blockHight: 未公布
    timeTitle: 发布日期
    timeTitleClass: silvertimetitle
    time: 未确定
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: silverhight
    timeClass: silver
    btnTitle: 查看详情
    btnHref: /pages/silverdetail.html
    stateTitle: 即将分叉
    state: 0
    stateColor: F99F26
    belong: btForkInfo
  - imageHref: /pages/bcddetail
    imageUrl: /resource/bcd.jpg
    coinName: 比特钻石(BCD)
    coinInfo: 团队预挖时间，主网尚未上线
    progress: 0
    progressTitle: 0%
    blockHightTitle: 分叉高度
    blockHight: 495866
    timeTitle: 倒计时
    timeTitleClass: bcdtimetitle
    time: 0
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: bcdhight
    timeClass: btcd
    btnTitle: 查看详情
    btnHref: /pages/bcddetail
    stateTitle: 分叉中
    state: 2
    stateColor: ED6363
    belong: btForkInfo
  - imageHref: /pages/btgdetail
    imageUrl: /resource/btg.jpg
    coinName: 比特金(BTG)
    coinInfo: 通过改变挖矿算法打破算力垄断
    progress: 100
    progressTitle: 100%
    blockHightTitle: 分叉高度
    blockHight: 491407
    timeTitle: 倒计时
    time: 0
    timeTitleClass: btgtimetitle
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: btghight
    timeClass: btg
    btnTitle: 查看详情
    btnHref: /pages/btgdetail
    stateTitle: 已分叉
    state: 1
    stateColor: 3AACEB
    belong: btForkInfo
  - imageHref: /pages/bchdetail
    imageUrl: /resource/bch.jpg
    coinName: 比特现金(BCH)
    coinInfo: 点对点电子现金
    progress: 100
    progressTitle: 100%
    blockHightTitle: 分叉高度
    blockHight: 478558
    timeTitle: 倒计时
    time: 0
    timeTitleClass: bchtimetitle
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: bchhight
    timeClass: bch
    btnTitle: 查看详情
    btnHref: /pages/bchdetail
    stateTitle: 已分叉
    state: 1
    stateColor: 3AACEB
    belong: btForkInfo
  - imageHref: /pages/b2xdetail
    imageUrl: /resource/default.jpg
    coinName: Bitcoin Segwit 2X(B2X)
    coinInfo: 纽约共识确定的隔离验证+2X方案
    progress: 100
    progressTitle: 100%
    blockHightTitle: 分叉高度
    blockHight: 494784
    timeTitle: 已取消
    time: 0
    timeTitleClass: b2xtimetitle
    currentHightTitle: 当前块高
    currentHight: 加载中
    currentHightClass: b2xhight
    timeClass: b2x
    btnTitle: 查看详情
    btnHref: /pages/b2xdetail
    stateTitle: 已取消
    state: 3
    stateColor: C8C8C8
    belong: btForkInfo

candyInfo:
  - imageHref: /pages/byteballdetail
    imageUrl: /resource/byteball.jpg
    coinName: 雪球币
    coinInfo: 去中心化的系统，允许任意数据的防篡改存储，包括可转移价值的数据，如货币，产权，债务，股份等。
    btnTitle: 查看详情
    btnHref: /pages/byteballdetail
    stateTitle: 进行中
    state: 1
    stateColor: F99F26
  - imageHref: /pages/btxdetail
    imageUrl: /resource/btx.jpg
    coinName: BTX
    coinInfo: 比特币的复制网络，通过派发糖果方式给比特币持有者发币。
    btnTitle: 查看详情
    btnHref: /pages/btxdetail
    stateTitle: 进行中
    state: 1
    stateColor: F99F26
  - imageHref: /pages/stellardetail
    imageUrl: /resource/stellar.jpg
    coinName: 恒星币
    coinInfo: 价值交换的开源协议。
    btnTitle: 查看详情
    btnHref: /pages/stellardetail
    stateTitle: 已结束
    state: 0
    stateColor: C8C8C8
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
